name: build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Enable arm64 apt architecture
      run: |
        sudo dpkg --add-architecture arm64
        sudo sed -i 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
    - name: Linux setup
      run: |
        sudo apt-get install -y \
          g++-12-aarch64-linux-gnu \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev:arm64 \
          libc-ares-dev:arm64 \
          zlib1g-dev:arm64 \
          libsqlite3-dev:arm64 \
          libssh2-1-dev:arm64
    - name: Setup cross compiler
      run: |
        echo 'CC=aarch64-linux-gnu-gcc-12' >> $GITHUB_ENV
        echo 'CXX=aarch64-linux-gnu-g++-12' >> $GITHUB_ENV
        echo 'AR=aarch64-linux-gnu-ar' >> $GITHUB_ENV
    - name: Libtool
      run: |
        autoreconf -i
    - name: Setup compiler flags
      run: |
        echo "CPPFLAGS=-O2" >> $GITHUB_ENV
    - name: Configure autotools
      run: |
        ./configure \
          --host=aarch64-linux-gnu \
          --without-gnutls \
          --with-openssl
    - name: Build aria2
      run: |
        make -j"$(nproc)"
    - name: Strip binary
      run: |
        aarch64-linux-gnu-strip src/aria2c
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2c-linux-arm64
        path: src/aria2c
