name: build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Linux setup
      run: |
        sudo apt-get update
        sudo apt-get install \
          g++-12 \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libc-ares-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev
    - name: Setup gcc
      run: |
        echo 'CC=gcc-12' >> $GITHUB_ENV
        echo 'CXX=g++-12' >> $GITHUB_ENV
    - name: Libtool
      run: |
        autoreconf -i
    - name: Setup compiler flags
      run: |
        asanflags="-fsanitize=address,undefined -fno-sanitize-recover=undefined"
        echo "CPPFLAGS=$asanflags -g3" >> $GITHUB_ENV
        echo "LDFLAGS=$asanflags" >> $GITHUB_ENV
    - name: Configure autotools
      run: |
        ./configure --without-gnutls --with-openssl
    - name: Build aria2
      run: |
        make -j"$(nproc)"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2c-linux
        path: src/aria2c
